name: Lint

on:
  push:

jobs:
  lint:
    name: Run lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install dependencies
        run: pip install tox
      - name: Lint
        run: tox -e lint,security
